apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: nginx # label selectors Pod
  ports:
    - port: 81 # port of the serivce
      targetPort: 80 # port of the container that service will forward to 