apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv 
spec:
  storageClassName: mystorage
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /mnt/nfs_share/
    server: 172.16.1.89 
    readOnly: false