apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
  labels:
    app: netbox
spec:
  storageClassName: mystorage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi